### ISSUE TITLE
API integration

### ISSUE THREAD

**Issue by jamesgeddes** [niorad/DevLids-Web-Components-Front-End#11]
May I request an API that would allow us to do [GeekZoneHQ/web#435](https://github.com/GeekZoneHQ/web/issues/435), please?

Should allow user to submit image or image URL, username, tags. Should respond with devlids.com url.

**Comment by niorad** [comment]
Thanks for your suggestion.
I do not have time to implement an API. Also this would multiply the time needed to run and maintain the site, which I hardly get around to manage as-is.

**Comment by jamesgeddes** [comment]
If you were to add an open source licence to this project, perhaps others could help? I was not necessarily saying you had to implement this yourself @niorad :smile:

**Comment by niorad** [comment]
@jamesgeddes I'm using Kirby-CMS as CMS for the site, which is non-free to use. And the images of the lids belong to their owners/makers. So there's not exactly lots of material for me to open-source.

**Comment by jamesgeddes** [comment]
Perhaps we will set [GeekZoneHQ/web#435](https://github.com/GeekZoneHQ/web/issues/435) to send you an email with usernames and an image attached then. Would that work for you?

**Comment by niorad** [comment]
Yes this would be perfect, if you send it to submit at devlids dot com
It would be important to have either an email-address from the submitter, or their twitter/github-username, or at least a name. Tags won't be needed, since I'm tagging the lids myself. Thank you!

**Comment by jamesgeddes** [comment]
How does  [GeekZoneHQ/web#435](https://github.com/GeekZoneHQ/web/issues/435) look now?

Do you always set the URL to https://devlids.com/lids/USERNAME?

**Comment by niorad** [comment]
Yes, always like this. The usernames I enter (usually twitter-names or first-names) get slugified by kirby, so it may not always be 1:1.

**Comment by jamesgeddes** [comment]
Thanks

How does  [GeekZoneHQ/web#435](https://github.com/GeekZoneHQ/web/issues/435) look now? Does that email format work for you?

**Comment by niorad** [comment]
- You can leave out the tags
- Email is not required, but I need one of email or active twitter-username (in order to get in touch with the submitter).
- Full name is not required, but if there is no twitter/github/devto-name, I need some (nick-)name for the page-title and URL.
- It should be understood that this is not an automated process and it can take some weeks until a submission is on the page. Once it's online, I'm notifying the submitter via twitter or email.

**Comment by jamesgeddes** [comment]
All good!

Regarding.
- tags, could we also include "Geek.Zone" in any that come from us? That's why I've suggested that we include it, just for your convenience.
- email address, all emails will come from support@geek.zone, so the email address provided will be for the member.
- Full name, we will ask the member to provide at least one of those fields if they want to send their lid to you.
- Lead time, we will make it clear that publication will not happen before a few weeks.

**Comment by niorad** [comment]
You can add the tag, but it will only be included on the lid-detail-page if it's a sticker on the lid.
The geekzone-email is fine, as long as the user can receive my response at that address.

**Comment by jamesgeddes** [comment]
We could potentially send it from the `member name`@geek.zone address, but sending it from support@geek.zone would be much easier. We could set the `Reply-To` address as `member email address` if that works for you?

**Comment by niorad** [comment]
Yes, that should be good, thanks.
